### PR TITLE
Expand on usage of examples

### PR DESCRIPTION
**Pull request by luckynumberke7in**
Created a simple README.md to show the steps for how someone can successfully run the examples.

### CODE REVIEW

**Comment by luckynumberke7in** [comment]
I had a bit of a hiccup getting this to work due to the `path` of this package in `Cargo.toml` and figured maybe I could help someone else dodge my pain =)

I'm unsure of other ways (maybe an even easier way to get these examples running)?

Please feel free to let me know if there are better ways!

**Comment by maccesch** [comment]
Thanks for trying to improve the docs!

However there is a readme in every example folder that describes how to run it. It is indeed different for different examples. The sqlx one uses cargo-leptos but most simply use trunk.

**Comment by luckynumberke7in** [comment]
Should I move this PR inside that specific example? I read the README.md inside the example 'serverfn_sqlx` also using `cargo leptos watch` but the information inside there didn't actually help me, personally.

**Comment by luckynumberke7in** [comment]
I ran into a strange situation where I was receiving error messages that made it seem like $PATH wasn't set up for Rust correctly on my new system which derailed me by more time than I'd like to admit...

I can only imagine there will be others on the more beginner end of Rust running into these same issues.

**Comment by luckynumberke7in** [comment]
Specifically, I was getting errors about reading the `Cargo.toml` file because you have the dependency set to `leptos-struct-table = { path = "../.." }` and I originally grabbed the example separately from the repo and missed this.

**Comment by maccesch** [comment]
Sure. We can add a sentence to each example readme that you need to make sure to have the whole repo checked out.

**Comment by luckynumberke7in** [comment]
Let me know what you think! I also added a touch of styling to the markdown.

**Comment by maccesch** [comment]
Thank you very much!

**Pull request merged**
